"""Added status track

Revision ID: 2968979b637c
Revises: 2a6d3647204c
Create Date: 2026-04-29 17:56:32.560174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2968979b637c'
down_revision: Union[str, Sequence[str], None] = '2a6d3647204c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ingestion_tasks')
    # ### end Alembic commands ###
